### PR TITLE
Circular maintenance

### PR DESCRIPTION
**Pull request by dakota002**

### CODE REVIEW

**Comment by dakota002** [comment]
@lpsinger This is becoming a pretty hefty PR, are there any parts that you think could be broken out into some smaller PRs to avoid crazy future merge conflicts?

**Comment by lpsinger** [comment]
> @lpsinger This is becoming a pretty hefty PR, are there any parts that you think could be broken out into some smaller PRs to avoid crazy future merge conflicts?

I would start with the back end.

**Comment by lpsinger** [comment]
Did we get all of the pieces of this onto main? Can we close it now?

**Comment by dakota002** [comment]
> Did we get all of the pieces of this onto main? Can we close it now?

Yup! I'll close it

**Pull request closed without merging**
