### PR TITLE
Fixes missing fields causing unexpected error in moderator views

### LINKED ISSUE #2431: Moderator page throws unexpected error if a Diff'd string is missing
# Current behavior
Unexpected Error prevents further interaction

# Expected behavior
Undefined strings should behave as empty strings to prevent the error from throwing

# Steps to reproduce
- Sign in as a moderator
- Navigate to the review page
- Review any current pending edit
-Error pops up

# Environment
All

### PR DESCRIPTION
**Pull request by dakota002**
Fixes #2431 

I am working on adding some playwright tests for this page, but this should resolve the issue so that we aren't blocked in approving changes

### CODE REVIEW

**Review by lpsinger — COMMENTED** [review]
It's the format field that was missing, isn't it? It's not an error for it to be missing.

**Comment by dakota002** [comment]
> It's the format field that was missing, isn't it? It's not an error for it to be missing.

Also the created on field, should I remove that message?

**Comment by lpsinger** [comment]
> > It's the format field that was missing, isn't it? It's not an error for it to be missing.
> 
> Also the created on field, should I remove that message?

If the field is absent in original _and_ in the new version, then of course that's not an error. If it's absent in the old version and present in the new version, then we should render that as if it was an empty string in the original. If it's present in the original but absent in the new version, well --- that should be impossible.

**Comment by dakota002** [comment]
> > > It's the format field that was missing, isn't it? It's not an error for it to be missing.
> > 
> > 
> > Also the created on field, should I remove that message?
> 
> If the field is absent in original _and_ in the new version, then of course that's not an error. If it's absent in the old version and present in the new version, then we should render that as if it was an empty string in the original. If it's present in the original but absent in the new version, well --- that should be impossible.

This was actually a case of the last one you mentioned, present in the original, missing in the new because the change requests were made before the UI supported createdOn being a changeable field

**Review by lpsinger — APPROVED** [review]

**Pull request merged**
