### PR TITLE
Fix for windows build

### PR DESCRIPTION
**Pull request by dakota002**
Can't build on my machine without this package

```
Error: The package "@esbuild/win32-x64" could not be found, and is needed by esbuild.

```

### CODE REVIEW

**Comment by lpsinger** [comment]
@dakota002, would you please open a separate PR to make the node.js GitHub workflow a matrix that runs on Ubuntu, macOS, and Windows, so that we catch things like in advance in the future?

And does rolling back to an earlier version of esbuild fix this? I would rather not add an unconditional dependency on binaries for a specific platform, which won't be used on other platforms.

**Comment by dakota002** [comment]
Sure, did we remove esbuild as a dependency in general? I dont see it in the dev deps, but I also just tried `npm install --save-exact --save-dev esbuild` and it is working again too

**Comment by lpsinger** [comment]
> Sure, did we remove esbuild as a dependency in general? I dont see it in the dev deps, but I also just tried `npm install --save-exact --save-dev esbuild` and it is working again too

It's a dependency of `@remix-run/dev`:

```
$ npm ls esbuild
@nasa-gcn/gcn.nasa.gov@ /Users/lpsinger/src/gcn.nasa.gov
└─┬ @remix-run/dev@2.0.1
  ├─┬ @vanilla-extract/integration@6.2.1
  │ ├── esbuild@0.17.6 deduped
  │ └─┬ vite@4.3.9
  │   └── esbuild@0.17.15
  ├─┬ esbuild-plugins-node-modules-polyfill@1.6.1
  │ └── esbuild@0.17.6 deduped
  └── esbuild@0.17.6
```

**Comment by lpsinger** [comment]
@dakota002, does it work if you do a fully clean build from the main branch? i.e., blow away `node_modules` first?

**Comment by dakota002** [comment]
Wow, yea apparently it did. I ran `npm run clean` without luck. Okay that just solved the problem. Thank you! We can just close this and that other matrix PR out

**Pull request closed without merging**
