### PR TITLE
Update deployment to Node.js 22.x

### PR DESCRIPTION
**Pull request by lpsinger**

### CODE REVIEW

**Comment by dakota002** [comment]
I don't believe this version is supported yet by architect

**Comment by lpsinger** [comment]
> I don't believe this version is supported yet by architect

It's not? Why do you say so?

**Comment by dakota002** [comment]
From trying it locally, 
image

And their build matrix on github:
image

**Comment by lpsinger** [comment]
Blocked by https://github.com/architect/lambda-runtimes/pull/8.

**Review by dakota002 — APPROVED** [review]

**Pull request merged**
