### PR TITLE
Place circulars table-stream Lambda inside our VPC

### PR DESCRIPTION
**Pull request by lpsinger**
This Lambda talks to our Kafka cluster, which in our dev deployment only accepts external traffic from the NASA network. Place the Lambda inside our VPC so that it can talk to the Kafka cluster regardless.

### CODE REVIEW

**Comment by lpsinger** [comment]
@dakota002, I've manually deployed this to dev. Would you please check if your Lambda can connect to the Kafka cluster now?

**Review by dakota002 — APPROVED** [review]

**Comment by dakota002** [comment]
Yea, I will run some tests now

**Comment by dakota002** [comment]
Still no luck, same error is getting thrown in cloudwatch

**Comment by lpsinger** [comment]
This didn't help. In this setup, the Lambda still resides “in” the AWS-managed VPC; Lambda VPC private networking simply sets up VPC-to-VPC NAT which is not sufficient to allow ingress given our existing NACLs.

**Pull request closed without merging**
