### PR TITLE
Remove 'submitted by' display

### LINKED ISSUE #1240: GCN Circulars: Remove submitted by
Just a quick fix, we had a discussion over removing the submitted by (legacy/web-form etc.) in the circulars, as we have inclusive policy.
But it would be nice to keep the information as a hidden file.

### PR DESCRIPTION
**Pull request by dakota002**
resolves #1240

### CODE REVIEW

**Comment by Vidushi-GitHub** [comment]
Thanks! Instead of removing totally, is it possible to store this info in some file? This information would be helpful for us at least for a year, to know how many users are still submitting to capella2, comfort with web-form etc.

**Comment by dakota002** [comment]
Yep! That should still happen. I only removed the display of the data

**Comment by lpsinger** [comment]
As I said in #1202, I see no reason for this information not to be public. In fact, I was thinking of adding some public statistics derived from this data.

**Comment by Vidushi-GitHub** [comment]
Ok, I see. Sorry my bad, I didn't follow. I have two reasons for my concern: (a) It feels like hacking someone's alert, especially when opening the JSON file submitted by doesn't fit. (b) Users should feel at ease for quickly sending the GCN, without the sense that their submission process is publicly known, and should switch to a specific method. If our intention is to encourage the use of the web form, then it's fine.
I agree it's good to show some statistics but I feel it should be done without identification of the specific users involved.

**Pull request closed without merging**
