### PR TITLE
Add Markdown editing and rendering support for Circulars

### PR DESCRIPTION
**Pull request by lpsinger**
This is currently hidden behind a feature flag until we have documentation and announcements for it.

# Screenshot

Screenshot 2024-02-14 at 13 37 33

### CODE REVIEW

**Comment by Vidushi-GitHub** [comment]
Cool work! I have two suggestions:

**Comment by Vidushi-GitHub** [comment]
Cool feature!

I have two suggestions:
(a) The content box looks a bit cut off from the upside, because of that it appears a bit crowded.
(b) What about adding a save button? back, save and send?

**Comment by tylerbarna** [comment]
It may be helpful to add a page to the documentation that explains what markdown is and the basic uses of it for circulars, something along the lines of [this](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) (but much more basic)

**Comment by lpsinger** [comment]
> (a) The content box looks a bit cut off from the upside, because of that it appears a bit crowded.

Fixed:

Screenshot 2024-02-14 at 14 42 27

> (b) What about adding a save button? back, save and send?

Like, to save a draft? Interesting idea, but that would be a significant new feature.

**Comment by lpsinger** [comment]
> It may be helpful to add a page to the documentation that explains what markdown is and the basic uses of it for circulars, something along the lines of [this](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) (but much more basic)

Definitely. I opened a separate issue for that: #1925.

**Pull request merged**
