### PR TITLE
Makes scope visible in Credential Cards

### LINKED ISSUE #760: Show credential scope to user for easier credentials management
For credentials that have already been created by a user, and shown on https://gcn.nasa.gov/user/credentials
there is no clear way to determine what scope they have!

eg, when testing I had to create a whole new credential to ensure that an issue was/wasn't caused by improper scope.

### PR DESCRIPTION
**Pull request by dakota002**
image

resolves #760

### CODE REVIEW

**Comment by lpsinger** [comment]
This changes the sizing of the box so that the Delete and Select buttons are no longer centered with the text.

How would it look if we decreased the size of the name ("Show me scope" here) to match the rest of the text, but kept it bold? Would that get us back to the original metrics?

**Comment by dakota002** [comment]
@lpsinger Here is an example with the smaller text and centered buttons:
image

**Comment by lpsinger** [comment]
That looks great. Can you post screenshots on a few different device sizes including mobile and tablet?

**Comment by dakota002** [comment]
Mobile:
image

Tablet:
image

**Review by lpsinger — APPROVED** [review]

**Pull request merged**
