### PR TITLE
Fixes Edit page loading and adds some simple playwright tests

### LINKED ISSUE #2368: Edit Circular form does not populate date and time fields
Please add some Playwright tests for Circulars submission, moderation, and editing workflows. We have a lot of broken corner cases.

# Current behavior

The date and time fields are blank.

Screenshot 2024-06-13 at 19 54 41

# Expected behavior

Fields should be populated

# Steps to reproduce

Navigate to https://dev.gcn.nasa.gov/circulars/edit/33671

# Environment

Safari, macOS

### PR DESCRIPTION
**Pull request by dakota002**
Resolves #2368

This will also require adding 2 new env variables, TEST_USERNAME and TEST_PASSWORD

### CODE REVIEW

**Comment by dakota002** [comment]
Adding another couple of tests still

**Comment by lpsinger** [comment]
> This will also require adding 2 new env variables, TEST_USERNAME and TEST_PASSWORD

Are you sure? The sandbox IdP will accept _any_ username and password.

**Comment by dakota002** [comment]
> > This will also require adding 2 new env variables, TEST_USERNAME and TEST_PASSWORD
> 
> Are you sure? The sandbox IdP will accept _any_ username and password.

True, but since these tests cover submission and corrections the test user will need the appropriate permissions

**Comment by lpsinger** [comment]
> > > This will also require adding 2 new env variables, TEST_USERNAME and TEST_PASSWORD
> > 
> > 
> > Are you sure? The sandbox IdP will accept _any_ username and password.
> 
> True, but since these tests cover submission and corrections the test user will need the appropriate permissions

How is that related to the username and password?

**Comment by lpsinger** [comment]
This is currently blocking deployments.

**Comment by dakota002** [comment]
> > > > This will also require adding 2 new env variables, TEST_USERNAME and TEST_PASSWORD
> > > 
> > > 
> > > Are you sure? The sandbox IdP will accept _any_ username and password.
> > 
> > 
> > True, but since these tests cover submission and corrections the test user will need the appropriate permissions
> 
> How is that related to the username and password?

The tests run `auth.setup.ts` first to sign in a user, then use that auth state for tests

**Comment by lpsinger** [comment]
> > > > > This will also require adding 2 new env variables, TEST_USERNAME and TEST_PASSWORD
> > > > 
> > > > 
> > > > Are you sure? The sandbox IdP will accept _any_ username and password.
> > > 
> > > 
> > > True, but since these tests cover submission and corrections the test user will need the appropriate permissions
> > 
> > 
> > How is that related to the username and password?
> 
> The tests run `auth.setup.ts` first to sign in a user, then use that auth state for tests

Yes, but the sandbox IdP will accept _any_ username and password --- it doesn't even check them. Why not just hardcode some arbitrary string?

**Comment by dakota002** [comment]
> > > > > > This will also require adding 2 new env variables, TEST_USERNAME and TEST_PASSWORD
> > > > > 
> > > > > 
> > > > > Are you sure? The sandbox IdP will accept _any_ username and password.
> > > > 
> > > > 
> > > > True, but since these tests cover submission and corrections the test user will need the appropriate permissions
> > > 
> > > 
> > > How is that related to the username and password?
> > 
> > 
> > The tests run `auth.setup.ts` first to sign in a user, then use that auth state for tests
> 
> Yes, but the sandbox IdP will accept _any_ username and password --- it doesn't even check them. Why not just hardcode some arbitrary string?

This is half way to the solution, my latest commit now uses this. The other thing is that the fake account just needed the additional  cognito groups and if you test this locally just make sure you switch to using the sandbox mode if you aren't already

**Comment by lpsinger** [comment]
> > > > > > > This will also require adding 2 new env variables, TEST_USERNAME and TEST_PASSWORD
> > > > > > 
> > > > > > 
> > > > > > Are you sure? The sandbox IdP will accept _any_ username and password.
> > > > > 
> > > > > 
> > > > > True, but since these tests cover submission and corrections the test user will need the appropriate permissions
> > > > 
> > > > 
> > > > How is that related to the username and password?
> > > 
> > > 
> > > The tests run `auth.setup.ts` first to sign in a user, then use that auth state for tests
> > 
> > 
> > Yes, but the sandbox IdP will accept _any_ username and password --- it doesn't even check them. Why not just hardcode some arbitrary string?
> 
> This is half way to the solution, my latest commit now uses this. The other thing is that the fake account just needed the additional cognito groups and if you test this locally just make sure you switch to using the sandbox mode if you aren't already

So we need to pre-populate the sandbox IdP with some fake accounts with predefined group claims.

**Comment by dakota002** [comment]
For the scope of this issue, i think it will be fine as is. I do not know what crazy config changes we will also need to make to the playwright.config file to point to specific auth states per test, or there is probably another solution in just running some auth steps before the tests directly, but again I think that would be best left to a separate issue 

 The tests failed, but just because of some timeouts. I have another commit to push if they timeout again that may help

**Review by lpsinger — CHANGES_REQUESTED** [review]

**Review by lpsinger — APPROVED** [review]

**Pull request merged**
