### PR TITLE
Simple plugin to add an S3 bucket to the cloudformation template

### PR DESCRIPTION
**Pull request by dakota002**
From [these docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html) it looks like all the properties are optional, so I think this should be enough to create the new S3 bucket

### CODE REVIEW

**Comment by lpsinger** [comment]
What about https://www.npmjs.com/package/@architect/plugin-storage-private?

**Comment by dakota002** [comment]
Neat! I read over their code a bit and seems straight forward, I'll try implementing it

**Comment by dakota002** [comment]
First bullet point of [1266](https://github.com/nasa-gcn/gcn.nasa.gov/issues/1266)

**Comment by lpsinger** [comment]
Closing in favor of similar change on the gan-infrastructure side.

**Pull request closed without merging**
