### PR TITLE
Create labs route with separate layout

### LINKED ISSUE #1582: Refactor GCN content and root routes into subfolder

### PR DESCRIPTION
**Pull request by lpsinger**
Fixes #1582.

### CODE REVIEW

**Comment by lpsinger** [comment]
This seems to be working fine except that the layout route `app/routes/_gcn+/circulars/route.tsx` is not being inherited by sub routes. Looks like a bug in https://github.com/kiliman/remix-flat-routes.

Screenshot 2023-11-03 at 12 17 15

@dakota002, @Courey, would one of you like to take on making reproducer for this, submitting at upstream as an issue, and attempting a fix?

**Comment by dakota002** [comment]
@lpsinger I believe it is being inherited, but the outlet defined at `app\routes\_gcn+\circulars._archive.tsx` is possibly conflicting with (and I am assuming overriding) `app\routes\_gcn+\circulars\route.tsx`

The `_archive.tsx` route is getting applied to specific circular pages too:
image

**Comment by lpsinger** [comment]
This is blocked by https://github.com/kiliman/remix-flat-routes/pull/83.

**Comment by lpsinger** [comment]
Closed in favor of #1651.

**Pull request closed without merging**
