### PR TITLE
Removes an unused css breakpoint to fix the overflow issue

### PR DESCRIPTION
**Pull request by dakota002**
Fixes this overflow issue:
image

### CODE REVIEW

**Comment by lpsinger** [comment]
Is there no way to do this with USWDS utility classes?

**Comment by dakota002** [comment]
There is, however they are bound to some parts in files we have ignored and which, I believe, are automatically built by gulp. The _uswds-theme-utilities.scss file has a width setting where responsive needs to be set to true

**Comment by lpsinger** [comment]
Which utility classes would do this?

**Comment by dakota002** [comment]
This one should be all we need: $width-settings

**Pull request merged**
