### PR TITLE
Schema: Parsing HEALPix Maps

### PR DESCRIPTION
**Pull request by Vidushi-GitHub**
@israelmcmc and @lpsinger 
As per earlier discussions, we are in the process of preparing instructions on how to parse the HEALPix maps. Please feel free to add basic content for the notice producers. 
Thanks!

This PR is in continuation of #950

### CODE REVIEW

**Comment by israelmcmc** [comment]
Thanks @Vidushi-GitHub. I have it my todo list, I'll make some time to work on this.

**Comment by Vidushi-GitHub** [comment]
@israelmcmc a gentle reminder. It would be helpful if you share the document, I can attempt to write. 
@jracusin please list out the all possible libraries for reference, I can add it.

**Comment by jracusin** [comment]
> @israelmcmc a gentle reminder. It would be helpful if you share the document, I can attempt to write. @jracusin please list out the all possible libraries for reference, I can add it.

mhealpy
astropy heal-is

**Comment by lpsinger** [comment]
There is also this documentation which is a good source: https://emfollow.docs.ligo.org/userguide/tutorial/multiorder_skymaps.html

**Comment by Vidushi-GitHub** [comment]
Work in progress in PR https://github.com/nasa-gcn/gcn.nasa.gov/pull/2498

**Pull request closed without merging**
