### PR TITLE
Adds some minor validation to catch html in the contact form fields

### PR DESCRIPTION
**Pull request by dakota002**
This will hopefully reduce the spam tickets we receive 

@lpsinger @Courey Please let me know if there are additional options you can think of to catch other potentially malicious requests

### CODE REVIEW

**Comment by lpsinger** [comment]
I don't know about this. Legitimate support requests could contain markup.

**Comment by dakota002** [comment]
Hm that is fair. What are your thoughts on updating it so that at least the checks against the subject, name, and email are not containing any, and a server side update that the email is address is correctly formatted? 

Also are there any different checks you think we should add?

**Review by lpsinger — COMMENTED** [review]
I am concerned that this might exclude legitimate content, especially content that contains sample XML content from VOEvents.

**Comment by dakota002** [comment]
Right, what are your thoughts on my previous comment though? Email Name and Subject fields only then?

**Comment by lpsinger** [comment]
> Right, what are your thoughts on my previous comment though? Email Name and Subject fields only then?

I can imagine that the subject field might also legitimately contain markup.

**Comment by dakota002** [comment]
Gotcha, what is your preference for this PR? Close out, or some changes?

**Comment by lpsinger** [comment]
I'm looking at the names on the tickets that we marked as spam, and this pattern would catch only some of them. It sure would be nice to have some spam filtering for tickets opened through the web form, but I think it would have to be a bit more sophisticated than a single regex.

**Pull request closed without merging**
