### PR TITLE
Add optional revisedOn field to circular and update approveChangeRequest method

### PR DESCRIPTION
**Pull request by dakota002**

### CODE REVIEW

**Review by lpsinger — CHANGES_REQUESTED** [review]
I like this, but could we rename the `editedBy` field to `revisedBy` for consistency? Would that require any database migration?

Alternatively, we could rename `revisedOn` to `editedOn`.

**Comment by lpsinger** [comment]
> > I like this, but could we rename the `editedBy` field to `revisedBy` for consistency? Would that require any database migration?
> > Alternatively, we could rename `revisedOn` to `editedOn`.
> 
> I think the latter will be easier, thought I also don't think there would be any migration required with the former

We don't have any existing database entries that would contain that field?

**Comment by dakota002** [comment]
> > > I like this, but could we rename the `editedBy` field to `revisedBy` for consistency? Would that require any database migration?
> > > Alternatively, we could rename `revisedOn` to `editedOn`.
> > 
> > 
> > I think the latter will be easier, thought I also don't think there would be any migration required with the former
> 
> We don't have any existing database entries that would contain that field?

We shouldn't since this is in support of the versioning feature which isn't out yet

**Comment by lpsinger** [comment]
> > > > I like this, but could we rename the `editedBy` field to `revisedBy` for consistency? Would that require any database migration?
> > > > Alternatively, we could rename `revisedOn` to `editedOn`.
> > > 
> > > 
> > > I think the latter will be easier, thought I also don't think there would be any migration required with the former
> > 
> > 
> > We don't have any existing database entries that would contain that field?
> 
> We shouldn't since this is in support of the versioning feature which isn't out yet

Alright. As for the naming of these two fields, which names (or what names) would be most similar to terminology used in the [DataCite REST API](https://support.datacite.org/docs/api)?

**Comment by dakota002** [comment]
> > > > > I like this, but could we rename the `editedBy` field to `revisedBy` for consistency? Would that require any database migration?
> > > > > Alternatively, we could rename `revisedOn` to `editedOn`.
> > > > 
> > > > 
> > > > I think the latter will be easier, thought I also don't think there would be any migration required with the former
> > > 
> > > 
> > > We don't have any existing database entries that would contain that field?
> > 
> > 
> > We shouldn't since this is in support of the versioning feature which isn't out yet
> 
> Alright. As for the naming of these two fields, which names (or what names) would be most similar to terminology used in the [DataCite REST API](https://support.datacite.org/docs/api)?

I don't see any attributes that are really similar. They have a `date` and a `version` property, but i don't see anything about editors, revisions, or dates relating to those ideas

**Review by lpsinger — APPROVED** [review]

**Pull request merged**
