### PR TITLE
add AMON, NuEM circulars keywords

### PR DESCRIPTION
**Pull request by jracusin**

### CODE REVIEW

**Comment by lpsinger** [comment]
The GitHub Actions workflow failed due to a network glitch. Would you please cancel and restart the workflow?

**Comment by jracusin** [comment]
I restarted it.  Did that work?

**Review by dakota002 — APPROVED** [review]

**Comment by lpsinger** [comment]
Thanks. I am working on a manual deployment right now because there are some DynamoDB changes from the last deployment. I'll let you know when this is live in production.

**Comment by lpsinger** [comment]
Deployment complete.

**Pull request merged**
